version: "3"

services:
  app:
    image: registry.gitlab.com/freden/smart-fridge:latest
    ports:
      - 80:8080
    environment:
      - "quarkus.mongodb.connection-string=mongodb://root:passwordsecure@mongo:27017"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
